# Generated by Django 5.2.1 on 2025-05-24 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('comedy', 'Comedy'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('historical', 'Historical'), ('psychological', 'Psychological'), ('shounen', 'Shounen'), ('shoujo', 'Shoujo'), ('art', 'Art'), ('sport', 'Sport'), ('romantic', 'Romantic')], max_length=100)),
                ('status', models.CharField(choices=[('not started', 'Not Started'), ('want to rewatch', 'Want To Rewatch'), ('not finished', 'Not Finished'), ('in progress', 'In Progress'), ('done', 'Done')], max_length=100)),
                ('score', models.IntegerField()),
                ('list_of_titles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.listoftitles')),
            ],
        ),
    ]
